# -*- coding: utf-8 -*-
"""posts_collector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vIcOOKZAZU2XA_rc1oF3oKT792-qiymO
"""

import pandas as pd

name1 = "2024-03-03_12_40_01.xlsx"

df1 = pd.read_excel(name1, header = 1)

df1.head()

df2 = pd.read_excel(name2, header = 1)

df2.head()

df = pd.concat([df1, df2])

df = df1

df = df.drop(columns=['Социальная сеть', 'Эмоциональный окрас', 'Лайков', 'Репостов', 'Просмотров', 'Негативных комментариев', 'Позитивных комментариев', 'Нейтральных комментариев', 'Неопределенных комментариев', 'Вежливых комментариев', 'Юмористических комментариев', 'Ссылка на пост', 'Текст', 'Дата'])

df.head()

df = df[df['Комментариев'] > 0]

df.head()

groups = df['Владелец'].unique()

groups

openness = df[df['Владелец'] == 'Хабр']

not_openness = df[df['Владелец'] == 'Консерватор']

openness.head()

conscientiousness = df[df['Владелец'] == 'ПБК ЦСКА']
not_conscientiousness = df[df['Владелец'] == 'Паша и его прокрастинация']
extroversion =  df[df['Владелец'] == 'Странная Планета / Strange Planet']
not_extroversion =  df[df['Владелец'] == 'Грусть']
agreeableness = df[df['Владелец'] == 'Благотворительный фонд Дети-ждут.рф']
not_agreeableness = df[df['Владелец'] == 'Черный список | Рынок Садовод']
neuroticism = df[df['Владелец'] == 'Типичный невротичный (ТЫ)']
not_neuroticism = df[df['Владелец'] == 'Psychology|Психология']

#openness.to_csv("openess.csv", sep=';', encoding='utf-8')
#not_openness.to_csv("not_openness.csv", sep=';', encoding='utf-8')

#conscientiousness.to_csv("conscientiousness.csv", sep=';', encoding='utf-8')
not_conscientiousness.to_csv("not_conscientiousness.csv", sep=';', encoding='utf-8')

extroversion.to_csv("extroversion.csv", sep=';', encoding='utf-8')
#not_extroversion.to_csv("not_extroversion.csv", sep=';', encoding='utf-8')

#agreeableness.to_csv("agreeableness.csv", sep=';', encoding='utf-8')
not_agreeableness.to_csv("not_agreeableness.csv", sep=';', encoding='utf-8')

#neuroticism.to_csv("neuroticism.csv", sep=';', encoding='utf-8')
#not_neuroticism.to_csv("not_neuroticism.csv", sep=';', encoding='utf-8')

neuroticism.head()

openess.head()